<a href="https://colab.research.google.com/github/maliwant/data_viz/blob/main/More_advanced_data_structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ที่เรียนไปแล้วมี 1ตัว คือ list หน้าตาประมาณนี้

##Dictionary

สามารถ index ด้วยอะไรก็ได้ แต่ว่าลำดับจะหาย


In [ ]:
ex_dict = {'a':10,'1':1,'stat':5} #curly brackets ในการบอกว่าเป็น dict

In [ ]:
ex_dict['stat']

5

In [ ]:
ex2_dict = {0:'zero',1: 'one',2:'two',3:'three'}

In [ ]:
ex2_dict[2]

'two'

#การเพิ่มสมาชิก

In [ ]:
ex2_dict[2] = 'zero'

In [ ]:
ex2_dict

{0: 'zero', 1: 'one', 2: 'zero', 3: 'three'}

In [ ]:
ex2_dict.keys()

dict_keys([0, 1, 2, 3])

In [ ]:
for index in ex2_dict.keys() :
  print(index)

0
1
2
3


In [ ]:
ex2_dict.values()

dict_values(['zero', 'one', 'zero', 'three'])

In [ ]:
index

3

#Number array

numpy คือ package ที่ทำงานเกี่ยวกับ array ของตัวเลข (ที่มีคนเขียนขึ้นมาและนิยมใช้) 
numpy-> number pyton

In [ ]:
import numpy #วิธีเรียกใช้ package

In [ ]:
ex_2d_array = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


#การชี้ค่าใน  numpy array

In [ ]:
ex_2d_array[1,2]

0.3

In [ ]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3],0.7,0.1] #การชี้ list #นับตามสมาชิกในวงเล็บใหญ่
print(len(list_x))

print(list_x[1])

print(list_x[1][2])

4
[9.1, 0.1, 0.3]
0.3


#operations

In [ ]:
ex2_2d_array = numpy.array([[1,0,0],[0,0,1]])
print(ex2_2d_array)
print(ex_2d_array)

[[1 0 0]
 [0 0 1]]
[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [ ]:
ex_2d_array.shape #ตรวจสอบขนาดของ matrix

(2, 3)

In [ ]:
ex_2d_array + ex2_2d_array

array([[6.2, 3. , 4.5],
       [9.1, 0.1, 1.3]])

In [ ]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
list_x2 = [[1,0,0],[0,0,1]]

list_x + list_x2

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3], [1, 0, 0], [0, 0, 1]]

In [ ]:
ex_2d_array - ex2_2d_array

array([[ 4.2,  3. ,  4.5],
       [ 9.1,  0.1, -0.7]])

In [ ]:
ex_2d_array * ex2_2d_array #การคูณแบบ array เอาตำแหน่งเดียวกันมาคูณกัน

array([[5.2, 0. , 0. ],
       [0. , 0. , 0.3]])

In [ ]:
numpy.dot(ex_2d_array,ex_2d_array)

In [ ]:
print(ex_2d_array)
print(ex_2d_array.T)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[5.2 9.1]
 [3.  0.1]
 [4.5 0.3]]


In [ ]:
dot_mat = numpy.dot(ex_2d_array,ex2_2d_array.T)
print(dot_mat)

[[5.2 4.5]
 [9.1 0.3]]


In [ ]:
numpy.linalg.det(dot_mat)

-39.389999999999986

#matrix slicing

In [ ]:
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [ ]:
ex_2d_array[1,1:]

array([0.1, 0.3])

In [ ]:
ex_2d_array[:,:2]

array([[5.2, 3. ],
       [9.1, 0.1]])

#HW 5 เขียน function คูณ matrix

แล้ว test กับ matrix

- (2'3)*(3'2)
- (4,4)*(4,1)
- (2,2)*(2,2)

In [ ]:
import numpy 
a1= numpy.array([[1,0,2],[2,2,3]])  #เมทริกซ์ 2 * 3 
a2 = numpy.array([[1,2],[3,2],[4,5]])  #เมทริกซ์ 3 * 2
print(a1)
print(a2)

[[1 0 2]
 [2 2 3]]
[[1 2]
 [3 2]
 [4 5]]


In [ ]:
b1 =  numpy.array([[1,2,3,4],[5,6,7,8],[10,12,14,5],[6,5,8,9]])  #เมทริกซ์ 4 * 4
b2 =  numpy.array([[2],[3],[4],[7]])    #เมทริกซ์ 4 * 1
print(b1)
print(b2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 12 14  5]
 [ 6  5  8  9]]
[[2]
 [3]
 [4]
 [7]]


In [ ]:
c1 = numpy.array([[9,5],[4,2]])   #เมทริกซ์ 2 * 2
c2 = numpy.array([[2,2],[4,5]])   #เมทริกซ์ 2 * 2
print(c1)
print(c2)

[[9 5]
 [4 2]]
[[2 2]
 [4 5]]


In [ ]:
def matrix(a1, a2) :
    mt = [[0 for row in range(len(a2[0]))] for col in range(len(a1))]
    for i in range(len(a1)) :
        for j in range(len(a2[0])) :
            for k in range(len(a2)) :
                mt[i][j] += a1[i][k]*a2[k][j]
    A = numpy.matrix(mt)
    return A

In [ ]:
matrix (a1,a2)

matrix([[ 9, 12],
        [20, 23]])

In [ ]:
matrix(b1,b2)

matrix([[ 48],
        [112],
        [147],
        [122]])

In [ ]:
matrix(c1,c2)

matrix([[38, 43],
        [16, 18]])

In [ ]:
a1a2 = numpy.dot(a1,a2) #ข้อ1 
print(a1a2)

[[ 9 12]
 [20 23]]


In [ ]:
b1b2 = numpy.dot(b1,b2) #ข้อ2 
print(b1b2)

[[ 48]
 [112]
 [147]
 [122]]


In [ ]:
c1c2 = numpy.dot(c1,c2) #ข้อ3
print(c1c2)

[[38 43]
 [16 18]]


#random , ones , zeros  

In [3]:
import numpy as np #import numpy แล้วตั้ง  np


##Zeros


In [7]:
np.zeros(2)

array([0., 0.])

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

##ones

In [9]:
np.ones((2,3))


array([[1., 1., 1.],
       [1., 1., 1.]])

#Matrix operation (scalar multiplication)

In [ ]:
M_one = np.ones(())

##random

In [10]:
np.random.rand(3,2) #uniform random [0,1)

array([[0.1980604 , 0.0312757 ],
       [0.44658373, 0.98219755],
       [0.15706872, 0.65215832]])

In [12]:
np.random.randn(3,2) # sample from nomal distribution mean = 0 std = 1

array([[ 0.19996637, -0.07795275],
       [-0.07437218,  1.18508641],
       [ 0.43320709,  0.67891826]])

In [13]:
np.random.choice([1,2,3,'a','b','c'])

'c'

In [14]:
np.random.choice([1,2,3,28,29,30],size = 2)

array([29,  1])

In [15]:
np.random.choice([1,2,3,28,29,30],size = (2,3))

array([[29,  1, 29],
       [ 2,  1,  2]])

In [16]:
np.random.choice([1,2,3,28,29,30],size = (2,3), replace = False)

array([[28, 30,  2],
       [ 1,  3, 29]])

In [ ]:
np.random.choice(['A','B','C','D','F'],size=35, P = [0.1,0.2,0.4,0.29,0.01])

#เฉลย HW Matrix multiplication

In [27]:
def mat_mul(A,B) :
  C = np.zeros((A.shape[0],B.shape[1])) #เตรียมขนาดของ matrix ผลลัพธ์
  for r_a in range(A.shape[0]) :
    for c_b in range(B.shape[1]) :
      for every_element in range(A.shape[1]) :
        C[r_a,c_b] = C[r_a,c_b] + A[r_a,every_element] * B[every_element,c_b]

In [28]:
mat1 = np.array([[1,2,3],[4,5,6]])
mat2 = np.array([[7,8],[9,10],[11,12]])

In [29]:
mat_mul(mat1,mat2)