<a href="https://colab.research.google.com/github/maliwant/data_viz/blob/main/More_advanced_data_structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ที่เรียนไปแล้วมี 1ตัว คือ list หน้าตาประมาณนี้

##Dictionary

สามารถ index ด้วยอะไรก็ได้ แต่ว่าลำดับจะหาย


In [1]:
ex_dict = {'a':10,'1':1,'stat':5} #curly brackets ในการบอกว่าเป็น dict

In [2]:
ex_dict['stat']

5

In [11]:
ex2_dict = {0:'zero',1: 'one',2:'two',3:'three'}

In [5]:
ex2_dict[2]

'two'

#การเพิ่มสมาชิก

In [12]:
ex2_dict[2] = 'zero'

In [13]:
ex2_dict

{0: 'zero', 1: 'one', 2: 'zero', 3: 'three'}

In [14]:
ex2_dict.keys()

dict_keys([0, 1, 2, 3])

In [15]:
for index in ex2_dict.keys() :
  print(index)

0
1
2
3


In [16]:
ex2_dict.values()

dict_values(['zero', 'one', 'zero', 'three'])

In [17]:
index

3

#Number array

numpy คือ package ที่ทำงานเกี่ยวกับ array ของตัวเลข (ที่มีคนเขียนขึ้นมาและนิยมใช้) 
numpy-> number pyton

In [18]:
import numpy #วิธีเรียกใช้ package

In [19]:
ex_2d_array = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


#การชี้ค่าใน  numpy array

In [20]:
ex_2d_array[1,2]

0.3

In [27]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3],0.7,0.1] #การชี้ list #นับตามสมาชิกในวงเล็บใหญ่
print(len(list_x))

print(list_x[1])

print(list_x[1][2])

4
[9.1, 0.1, 0.3]
0.3


#operations

In [30]:
ex2_2d_array = numpy.array([[1,0,0],[0,0,1]])
print(ex2_2d_array)
print(ex_2d_array)

[[1 0 0]
 [0 0 1]]
[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [32]:
ex_2d_array.shape #ตรวจสอบขนาดของ matrix

(2, 3)

In [31]:
ex_2d_array + ex2_2d_array

array([[6.2, 3. , 4.5],
       [9.1, 0.1, 1.3]])

In [33]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
list_x2 = [[1,0,0],[0,0,1]]

list_x + list_x2

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3], [1, 0, 0], [0, 0, 1]]

In [34]:
ex_2d_array - ex2_2d_array

array([[ 4.2,  3. ,  4.5],
       [ 9.1,  0.1, -0.7]])

In [35]:
ex_2d_array * ex2_2d_array #การคูณแบบ array เอาตำแหน่งเดียวกันมาคูณกัน

array([[5.2, 0. , 0. ],
       [0. , 0. , 0.3]])

In [ ]:
numpy.dot(ex_2d_array,ex_2d_array)

In [36]:
print(ex_2d_array)
print(ex_2d_array.T)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[5.2 9.1]
 [3.  0.1]
 [4.5 0.3]]


In [41]:
dot_mat = numpy.dot(ex_2d_array,ex2_2d_array.T)
print(dot_mat)

[[5.2 4.5]
 [9.1 0.3]]


In [42]:
numpy.linalg.det(dot_mat)

-39.389999999999986

#matrix slicing

In [43]:
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [45]:
ex_2d_array[1,1:]

array([0.1, 0.3])

In [47]:
ex_2d_array[:,:2]

array([[5.2, 3. ],
       [9.1, 0.1]])

#random , ones , zeros

#HW 5 เขียน function คูณ matrix

แล้ว test กับ matrix

- (2'3)*(3'2)
- (4,4)*(4,1)
- (2,2)*(2,2)